version: "3.9"
services:
  db:
    container_name: sql_agg
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: sql_agg
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - "./db-data:/var/lib/mysql"
      - "./schema.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./data.sql:/docker-entrypoint-initdb.d/2.sql"
